version: "3"
services:
  grafana:
    image: grafana/grafana-enterprise
    ports:
      - "3030:3000"
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"